languageCode:           "en"
title:                  "Jazz Boot"
#baseURL:                "https://pucsidesignsystemtest.z13.web.core.windows.net"
baseURL:               "https://princetonuniversityoit.github.io/jazz-boot"
canonifyurls:           true

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_site"

module:
  mounts:
    - source:           fonts
      target:           static/docs/5.1/dist/fonts
    - source:           dist
      target:           static/docs/5.1/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/5.1/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/5.1/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "The most popular HTML, CSS, and JS library in the world."
  authors:              "Mark Otto, Jacob Thornton, and Bootstrap contributors"
  social_image_path:    /docs/5.1/assets/brand/bootstrap-social.png
  social_logo_path:     /docs/5.1/assets/brand/bootstrap-social-logo.png

  current_version:      "5.1.3"
  current_ruby_version: "5.1.3"
  docs_version:         "5.1"
  rfs_version:          "v9.0.6"
  github_org:           "https://github.com/PrincetonUniversityOIT"
  repo:                 "https://github.com/PrincetonUniversityOIT/jazz-boot"
  twitter:              "null"
  slack:                "null"
  opencollective:       "null"
  blog:                 "null"
  themes:               "null"
  icons:                "https://icons.getbootstrap.com/"

  download:
    source:             "https://github.com/PrincetonUniversityOIT/jazz-boot/archive/refs/tags/1.0.0.zip"
    dist:               "https://github.com/PrincetonUniversityOIT/jazz-boot/releases/download/1.0.0/jazz-boot-dist.zip"
    dist_examples:      "https://github.com/PrincetonUniversityOIT/jazz-boot/releases/download/1.0.0/jazz-boot-examples.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "/dist/css/jazz.min.css"
    css_hash:         "sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    css_rtl:          "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.rtl.min.css"
    css_rtl_hash:     "sha384-+qdLaIRZfNu4cVPK/PxJJEy0B0f3Ugv8i482AKY7gwXwhaCroABd086ybrVKTa0q"
    js:               "/dist/js/jazz.min.js"
    js_hash:          "sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
    js_bundle:        "/dist/js/jazz.bundle.min.js"
    js_bundle_hash:   "sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.2/dist/umd/popper.min.js"
    popper_hash:      "sha384-q9CRHqZndzlxGLOj+xrdLDJa9ittGte1NksRmgJKeCV9DrM7Kz868XYqsKWPpAmn"

  anchors:
    min: 2
    max: 5
